# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='\u56de\u8986\u5167\u5bb9')),
                ('like', models.IntegerField(default=0, verbose_name='\u8b9a\u6578')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8a55\u8ad6\u56de\u8986',
                'verbose_name_plural': '\u8a55\u8ad6\u56de\u8986',
            },
        ),
        migrations.CreateModel(
            name='CommentPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8a55\u8ad6\u8b9a\u6578',
                'verbose_name_plural': '\u8a55\u8ad6\u8b9a\u6578',
            },
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='\u8a55\u8ad6')),
                ('like', models.IntegerField(default=0, verbose_name='\u8b9a\u6578')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4d\u7f6e')),
                ('picture', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5716\u6a94\u4f4d\u7f6e')),
                ('sound', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u8072\u97f3\u6a94\u4f4d\u7f6e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8ab2\u7a0b\u8a55\u8ad6',
                'verbose_name_plural': '\u8ab2\u7a0b\u8a55\u8ad6',
            },
        ),
        migrations.CreateModel(
            name='ReplyPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u56de\u8986\u8b9a\u6578',
                'verbose_name_plural': '\u56de\u8986\u8b9a\u6578',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u6a5f')),
                ('course_name', models.CharField(max_length=50, verbose_name='\u8ab2\u7a0b\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u7528\u6236\u8aee\u8a62',
                'verbose_name_plural': '\u7528\u6236\u8aee\u8a62',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8ab2\u7a0b')),
            ],
            options={
                'verbose_name': '\u8ab2\u7a0b\u7528\u6236',
                'verbose_name_plural': '\u8ab2\u7a0b\u7528\u6236',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6236')),
                ('message', models.CharField(max_length=500, verbose_name='\u6d88\u606f\u5167\u5bb9')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8b80')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u7528\u6236\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6236\u6d88\u606f',
            },
        ),
    ]
