# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('users', '0001_initial'),
        ('courses', '0002_auto_20170324_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtraProfile', verbose_name='\u7528\u6236'),
        ),
        migrations.AddField(
            model_name='replypostlike',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CommentComment', verbose_name='\u56de\u8986\u4e3b\u984c'),
        ),
        migrations.AddField(
            model_name='replypostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtraProfile', verbose_name='\u7528\u6236'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8ab2\u7a0b'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtraProfile', verbose_name='\u7528\u6236'),
        ),
        migrations.AddField(
            model_name='commentpostlike',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CourseComments', verbose_name='\u8a0e\u8ad6\u4e3b\u984c'),
        ),
        migrations.AddField(
            model_name='commentpostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtraProfile', verbose_name='\u7528\u6236'),
        ),
        migrations.AddField(
            model_name='commentcomment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CourseComments', verbose_name='\u8a0e\u8ad6\u4e3b\u984c'),
        ),
        migrations.AddField(
            model_name='commentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtraProfile', verbose_name='\u7528\u6236'),
        ),
    ]
