# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170324_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcomment',
            options={'verbose_name': '\u8a55\u8ad6\u5e95\u4e0b\u7684\u56de\u8986', 'verbose_name_plural': '\u8a55\u8ad6\u5e95\u4e0b\u7684\u56de\u8986'},
        ),
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': '\u8a0e\u8ad6\u5340\u7684\u8a55\u8ad6', 'verbose_name_plural': '\u8a0e\u8ad6\u5340\u7684\u8a55\u8ad6'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '\u7528\u6236\u6240\u9078\u7684\u8ab2\u7a0b', 'verbose_name_plural': '\u7528\u6236\u6240\u9078\u7684\u8ab2\u7a0b'},
        ),
    ]
