# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170503_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5f71\u7247\u6a94\u4f4d\u7f6e'),
        ),
    ]
