# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 00:37
from __future__ import unicode_literals

import courses.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8ab2\u7a0b\u540d')),
                ('desc', models.CharField(max_length=300, verbose_name='\u8ab2\u7a0b\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u8ab2\u7a0b\u8a73\u60c5')),
                ('instructor', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6307\u5c0e\u8001\u5e2b')),
                ('image', models.ImageField(blank=True, default='img/course/default_course.jpg', null=True, upload_to=courses.models.get_image_path)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8ab2\u7a0b',
                'verbose_name_plural': '\u8ab2\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6a19\u984c')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5167\u5bb9')),
                ('uploadFile', models.FileField(blank=True, null=True, upload_to=courses.models.get_courseHw_image_path, verbose_name='\u7bc4\u4f8b\u6a94\u6848')),
                ('limit_time', models.DateTimeField(default=datetime.datetime(2017, 3, 31, 0, 37, 25, 707845), verbose_name='\u7e73\u4ea4\u6642\u9593')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8ab2\u7a0b\u4f5c\u696d',
                'verbose_name_plural': '\u8ab2\u7a0b\u4f5c\u696d',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u7a31')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='\u6587\u4ef6\u63cf\u8ff0')),
                ('download', models.FileField(blank=True, null=True, upload_to=courses.models.get_courseResource_image_path, verbose_name='\u8cc7\u6e90\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u8ab2\u7a0b\u8cc7\u6e90',
                'verbose_name_plural': '\u8ab2\u7a0b\u8cc7\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ae0\u7bc0\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u7ae0\u7bc0',
                'verbose_name_plural': '\u7ae0\u7bc0',
            },
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8ab2\u7a0b')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseHomework', verbose_name='\u4f5c\u696d')),
            ],
            options={
                'verbose_name': '\u5b78\u751f\u4f5c\u696d\u4e0a\u50b3',
                'verbose_name_plural': '\u5b78\u751f\u4f5c\u696d\u4e0a\u50b3',
            },
        ),
    ]
