# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 01:01
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170324_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomework',
            name='limit_time',
            field=models.DateTimeField(default=courses.models.timeLimitSet, verbose_name='\u7e73\u4ea4\u6642\u9593'),
        ),
    ]
