# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 15:57
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170324_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_sh_path, verbose_name='\u6a94\u6848'),
        ),
    ]
