# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studenthomework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomework',
            name='deadline_token',
            field=models.CharField(choices=[('0', '\u5426'), ('1', '\u662f')], default='0', max_length=1, verbose_name='\u662f\u5426\u5230\u671f'),
        ),
    ]
