# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 00:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='\u4f7f\u7528\u8005')),
                ('name', models.CharField(default=' ', max_length=50, verbose_name='\u5b78\u865f')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6)),
                ('identify', models.CharField(choices=[('teacher', '\u8001\u5e2b'), ('student', '\u5b78\u751f')], default='\u5b78\u751f', max_length=7, verbose_name='\u8eab\u4efd')),
                ('image', models.ImageField(blank=True, default='img/user/default_user.png', null=True, upload_to=users.models.get_image_path)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u6642\u9593')),
            ],
            options={
                'verbose_name': '\u7528\u6236\u8cc7\u8a0a',
                'verbose_name_plural': '\u7528\u6236\u8cc7\u8a0a',
            },
        ),
    ]
