# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraprofile',
            options={'verbose_name': '\u4f7f\u7528\u8005\u984d\u5916\u8cc7\u8a0a', 'verbose_name_plural': '\u4f7f\u7528\u8005\u984d\u5916\u8cc7\u8a0a'},
        ),
    ]
